export { default as Main } from "./Main";
export { default as Dashboard } from "./Dashboard";
export { default as Auth } from "./Auth";
export { default as Accounts } from "./Accounts";
export { default as NotFound } from "./NotFound";
export { default as Notes } from "./Notes";
export { default as UserRules } from "./UserRules";
export { default as UserDepartments } from "./UserDepartments";
export { default as AuditLog } from "./Audit";
export { default as Categories} from "./Category";
export { default as Services} from "./Service";
export { default as Search} from "./Search";
